disabled_rules:
- todo
- trailing_whitespace

line_length: 300

function_body_length: 300

cyclomatic_complexity: 12

excluded: # paths to ignore during linting. Takes precedence over `included`.
- Pods
- R.generated.swift
- ParentView/Sources/Utils/DateHelper.swift

variable_name:
  excluded: # excluded via string array
    - ok
    - id
    - x
    - y
    - z
    - x0
    - xf
    - y0
    - yf
    - me
    - to
